### ISSUE TITLE
Enable Group Provisioning through user_oidc:provider Options

### ISSUE THREAD

**Issue by dcrosby** [nextcloud/user_oidc#793] opened 2024-02-15 20:19 UTC
The option to enable --groupProvider is missing from the other options to create a new provider instance when you list the help: **occ user_oidc:provider --help**

This is a severe limitation that greatly complicates the scripting/automation when creating the oidc provider instance.

**The result is that it requires multiple steps:**
1. Provision the Provider instance:  
```
occ user_oidc:provider [<identifier>] [options...]
```
4. Get the ID number of the provider instance that matches the <identifier> name: 
```
occ user_oidc:provider <instance_name>
```
5. Enable groupProvisioning using: 
```
occ config:app:set user_oidc --value=1 provider-<N>-groupProvisioning
```

**Solution:** 
Add the option to enable groupProvisioning at the time the provider is created so the groups can be enabled at the same time, and be enabled/disabled using the instance "Name" rather than the auto_increment ID number.

**Comment by col-panic** [comment] 2024-02-21 11:00
Relates to https://github.com/nextcloud/user_oidc/issues/791

**Comment by edward-ly** [comment] 2024-10-03 21:55
Closing as a duplicate of #791.

**Closed by edward-ly** 2024-10-03 21:55 UTC
Labels: enhancement, priority: normal
