### ISSUE TITLE
Unable to enable the app

### ISSUE THREAD

**Issue by istvan-berenyi** [nextcloud/user_oidc#121] opened 2020-11-10 23:16 UTC
OS; Centos 8
Nextcloud 20.1

Upon downloading the official OpenID app i'm unable to enable the app.
Error:

An error occured during the request. Unable to proceed.
Column name "oc_user_oidc"."display_name" is NotNull, but has empty string or null as default.

**Comment by aszlig** [comment] 2020-11-21 05:52
Duplicate of #90.

**Comment by kesselb** [comment] 2020-11-24 20:48
Duplicate of #90

**Closed** 2020-11-24 20:48 UTC
